cloud:
  aws:
    s3:
      bucket: 버킷명
    credentials:
      access-key: IAM 계정 - access key
      secret-key: IAM 계정 - secret access key
    region:
      static: 현재 s3 버킷의 Region
    stack:
      auto: false